export type ChannelDetails = {
        rowNumber: number,
        channelUrl: number,
        createdBy: string,
        views: number,
        likes: number,
        numVideos: number,
        followers: number,
        followPoints: string,
        points: string,
        imageUser: string,
        image: string,
        coverPhoto: string,
        days: string,
        cover: string,
        title: string,
        description: string,
        id: number,
        privacy: string,
        is_recommended: boolean,
        is_moderator: boolean,
        createdOn: string,
        user_id: string,
        name: string,
        thumbnail: string,
        ownerRank: string,
        ownerJoined: string,
        chViews:string,
        chVidsCount:string,
        chFollowers:string
}
export type ChannelFollowing = {
        id: number,
        channel_id: number,
        subscriber_user_id: string,
        is_approved: boolean,
        create_date: string,
        update_date: string,
        delete_date: any,
        channelName:string,
        followers:number,
        thumbnail:string
}